services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Kandoh\Lottie\:
        resource: '../Classes/*'

    Kandoh\Lottie\Backend\DisplayConditions:
        public: true
